# Generated by Django 5.1.2 on 2024-10-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdetails',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsessions'),
        ),
    ]
