# Generated by Django 5.1.2 on 2024-10-15 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_alter_chatdetails_session"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatUser",
            new_name="User",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
