# Generated by Django 5.1.2 on 2024-10-19 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_user_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatdetails",
            old_name="sender",
            new_name="role",
        ),
    ]
